### ISSUE TITLE
Add dark mode to app.

### ISSUE THREAD

**Issue by thisisamank** [thisisamank/resizrr#4]
Dark mode will look something like this:

| Home Screen<img src="https://user-images.githubusercontent.com/34718491/131282164-fc706c21-1c1d-4752-be46-91f934968bd7.png" style="zoom:60%;" /> | Filter Screen<img src="https://user-images.githubusercontent.com/34718491/131282169-2fba76a7-4c85-4ed1-8acc-074da7ab45d0.png" style="zoom:60%;" /> | Edit Screen<img src="https://user-images.githubusercontent.com/34718491/131282172-bb7b48cc-305c-4c14-af01-3ffe64c53808.png" style="zoom:60%;" /> | Main Screen<img src="https://user-images.githubusercontent.com/34718491/131282177-8155a6d0-2e69-40c6-a6e4-a948b4f02e27.png" style="zoom:60%;" /> |
| ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |

Hex code for `black` used: `#000000`

How to implement dark mode?
1. Create a class to fetch the current theme state from `shared preference`. Add methods to read, write & delete data to and from `shared preference`.
2. Add a class to contain `ThemeData` for light and dark mode. Add method to get current theme. Add methods to set light theme and set dark theme. Store the state to `shared preference` using the above class you created.

**Comment by adityaraj079** [comment]
@thisisamank can i work on this issue

**Comment by apoorva-raj** [comment]
Please assign me this issue !

**Comment by SushanShakya** [comment]
Hey, would love to work on dark mode.

**Comment by thisisamank** [comment]
Hi, This issue is already fixed, will add more issues soon :)
